[package]
name = "enderpy"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
unicode-id-start = "1.0.3"

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }


[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
