[package]
name = "typechecker"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
config = "0.13.3"
serde = { version = "1.0.164", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.28.0", features = ["yaml"] }
