[package]
name = "corepy_python_translator"
version = "0.1.0"
edition = "2021"

[dependencies]
enderpy_python_parser = { path = "../parser", version = "0.1.0" }
enderpy_python_type_checker = {path = "../typechecker", version = "0.1.0" }
log = { version = "0.4.17" }
