name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install nightly
        run: rustup toolchain install nightly
      - name: rustfmt
        run: cargo +nightly fmt --all -- --check
      - name: clippy
        run: cargo +nightly clippy --all --all-features --tests -- -D warnings