name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: rustfmt
        run: make format-check
      - name: clippy
        run: cargo clippy --all --all-features --tests -- -D warnings
